// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikpr_tT9NHjcGhtwUBrca2N7ojhq3oEI',
    appId: '1:67637962913:web:689eb0d573a83ea9be68e0',
    messagingSenderId: '67637962913',
    projectId: 'nimble-button-351312',
    authDomain: 'nimble-button-351312.firebaseapp.com',
    databaseURL: 'https://nimble-button-351312-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nimble-button-351312.appspot.com',
    measurementId: 'G-TGJ6X1X22F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmYLIlGVJuDpUMJOWkZmduew0F2Iprwzs',
    appId: '1:67637962913:android:94fc776636d12f33be68e0',
    messagingSenderId: '67637962913',
    projectId: 'nimble-button-351312',
    databaseURL: 'https://nimble-button-351312-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nimble-button-351312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTF9T1sn7zuB0LvLwkSkwzIv8pa4NY1QI',
    appId: '1:67637962913:ios:c57673096b1af643be68e0',
    messagingSenderId: '67637962913',
    projectId: 'nimble-button-351312',
    databaseURL: 'https://nimble-button-351312-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nimble-button-351312.appspot.com',
    iosClientId: '67637962913-e0ph8ta8g9mnusi9019bmm5fuq8lv51c.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectBus',
  );
}
